/**
 * lib/matchgifts-data.js — curated list of large employers commonly known to run
 * corporate matching-gift programs. This is a HEURISTIC nudge list, NOT an
 * authoritative database: matching is a standard benefit at most large employers,
 * so this covers the bulk of real matches by volume, but it is not exhaustive and a
 * given company's program can change. For full coverage (~24k companies) an org can
 * wire a commercial source (e.g. Double the Donation) — see docs/match-gifts.md.
 *
 * Each entry: { name (display), kw (lowercase keywords matched on word boundaries) }.
 * Keep keywords DISTINCTIVE — short/common words (e.g. "ge", "ice", "block") are
 * omitted on purpose to avoid false positives, since the donor message only ever
 * SUGGESTS the donor check their employer's portal (a human confirms before sending).
 */
export const MATCH_PROGRAMS = [
  // ── Technology & software ───────────────────────────────────────
  { name: 'Microsoft', kw: ['microsoft'] },
  { name: 'Google', kw: ['google', 'alphabet'] },
  { name: 'Apple', kw: ['apple'] },
  { name: 'Meta', kw: ['meta platforms', 'facebook', 'instagram', 'whatsapp'] },
  { name: 'Amazon', kw: ['amazon', 'aws'] },
  { name: 'Salesforce', kw: ['salesforce'] },
  { name: 'Adobe', kw: ['adobe'] },
  { name: 'Netflix', kw: ['netflix'] },
  { name: 'Nvidia', kw: ['nvidia'] },
  { name: 'Intel', kw: ['intel'] },
  { name: 'AMD', kw: ['amd', 'advanced micro devices'] },
  { name: 'Cisco', kw: ['cisco'] },
  { name: 'Oracle', kw: ['oracle'] },
  { name: 'IBM', kw: ['ibm'] },
  { name: 'SAP', kw: ['sap'] },
  { name: 'Dell', kw: ['dell'] },
  { name: 'HP', kw: ['hewlett-packard', 'hewlett packard', 'hp inc'] },
  { name: 'HPE', kw: ['hewlett packard enterprise', 'hpe'] },
  { name: 'Qualcomm', kw: ['qualcomm'] },
  { name: 'Broadcom', kw: ['broadcom'] },
  { name: 'Texas Instruments', kw: ['texas instruments'] },
  { name: 'Micron', kw: ['micron'] },
  { name: 'Applied Materials', kw: ['applied materials'] },
  { name: 'Analog Devices', kw: ['analog devices'] },
  { name: 'Marvell', kw: ['marvell'] },
  { name: 'Western Digital', kw: ['western digital'] },
  { name: 'Seagate', kw: ['seagate'] },
  { name: 'NetApp', kw: ['netapp'] },
  { name: 'Juniper Networks', kw: ['juniper'] },
  { name: 'Arista Networks', kw: ['arista'] },
  { name: 'Synopsys', kw: ['synopsys'] },
  { name: 'Cadence', kw: ['cadence design'] },
  { name: 'KLA', kw: ['kla corporation', 'kla-tencor'] },
  { name: 'Lam Research', kw: ['lam research'] },
  { name: 'Keysight', kw: ['keysight'] },
  { name: 'Motorola Solutions', kw: ['motorola'] },
  { name: 'Ericsson', kw: ['ericsson'] },
  { name: 'Nokia', kw: ['nokia'] },
  { name: 'Samsung', kw: ['samsung'] },
  { name: 'Sony', kw: ['sony'] },
  { name: 'Dolby', kw: ['dolby'] },
  { name: 'Logitech', kw: ['logitech'] },
  { name: 'LinkedIn', kw: ['linkedin'] },
  { name: 'Atlassian', kw: ['atlassian'] },
  { name: 'Stripe', kw: ['stripe'] },
  { name: 'PayPal', kw: ['paypal'] },
  { name: 'eBay', kw: ['ebay'] },
  { name: 'Intuit', kw: ['intuit'] },
  { name: 'ServiceNow', kw: ['servicenow'] },
  { name: 'Workday', kw: ['workday'] },
  { name: 'VMware', kw: ['vmware'] },
  { name: 'Autodesk', kw: ['autodesk'] },
  { name: 'Zoom', kw: ['zoom video'] },
  { name: 'DocuSign', kw: ['docusign'] },
  { name: 'Dropbox', kw: ['dropbox'] },
  { name: 'Splunk', kw: ['splunk'] },
  { name: 'Palo Alto Networks', kw: ['palo alto networks'] },
  { name: 'Okta', kw: ['okta'] },
  { name: 'Datadog', kw: ['datadog'] },
  { name: 'Snowflake', kw: ['snowflake'] },
  { name: 'Cloudflare', kw: ['cloudflare'] },
  { name: 'Akamai', kw: ['akamai'] },
  { name: 'Twilio', kw: ['twilio'] },
  { name: 'Pinterest', kw: ['pinterest'] },
  { name: 'Snap', kw: ['snap inc', 'snapchat'] },
  { name: 'Uber', kw: ['uber'] },
  { name: 'Lyft', kw: ['lyft'] },
  { name: 'Airbnb', kw: ['airbnb'] },
  { name: 'DoorDash', kw: ['doordash'] },
  { name: 'Instacart', kw: ['instacart'] },
  { name: 'Shopify', kw: ['shopify'] },
  { name: 'Coinbase', kw: ['coinbase'] },
  { name: 'Roblox', kw: ['roblox'] },
  { name: 'Electronic Arts', kw: ['electronic arts'] },
  { name: 'Activision Blizzard', kw: ['activision', 'blizzard'] },
  { name: 'Take-Two', kw: ['take-two', 'rockstar games'] },
  { name: 'Unity', kw: ['unity technologies'] },
  { name: 'Zillow', kw: ['zillow'] },
  { name: 'Yahoo', kw: ['yahoo'] },

  // ── Finance, banking & investing ────────────────────────────────
  { name: 'JPMorgan Chase', kw: ['jpmorgan', 'jp morgan', 'chase bank'] },
  { name: 'Goldman Sachs', kw: ['goldman sachs', 'goldman'] },
  { name: 'Morgan Stanley', kw: ['morgan stanley'] },
  { name: 'Bank of America', kw: ['bank of america', 'merrill lynch', 'merrill'] },
  { name: 'Wells Fargo', kw: ['wells fargo'] },
  { name: 'Citi', kw: ['citigroup', 'citibank'] },
  { name: 'Capital One', kw: ['capital one'] },
  { name: 'PNC', kw: ['pnc financial', 'pnc bank'] },
  { name: 'U.S. Bank', kw: ['u.s. bancorp', 'us bancorp', 'u.s. bank'] },
  { name: 'Truist', kw: ['truist'] },
  { name: 'American Express', kw: ['american express', 'amex'] },
  { name: 'Mastercard', kw: ['mastercard'] },
  { name: 'Visa', kw: ['visa'] },
  { name: 'Discover', kw: ['discover financial'] },
  { name: 'Synchrony', kw: ['synchrony'] },
  { name: 'Ally', kw: ['ally financial'] },
  { name: 'BlackRock', kw: ['blackrock'] },
  { name: 'State Street', kw: ['state street'] },
  { name: 'BNY Mellon', kw: ['bny mellon', 'bank of new york'] },
  { name: 'Northern Trust', kw: ['northern trust'] },
  { name: 'Charles Schwab', kw: ['charles schwab', 'schwab'] },
  { name: 'Fidelity', kw: ['fidelity investments', 'fmr llc'] },
  { name: 'Vanguard', kw: ['vanguard group', 'the vanguard'] },
  { name: 'T. Rowe Price', kw: ['t. rowe price', 't rowe price'] },
  { name: 'Raymond James', kw: ['raymond james'] },
  { name: 'Jefferies', kw: ['jefferies'] },
  { name: 'KKR', kw: ['kkr'] },
  { name: 'Blackstone', kw: ['blackstone'] },
  { name: 'Apollo', kw: ['apollo global'] },
  { name: 'Nasdaq', kw: ['nasdaq'] },
  { name: 'CME Group', kw: ['cme group'] },
  { name: 'S&P Global', kw: ['s&p global', 'standard & poor'] },
  { name: "Moody's", kw: ['moody'] },
  { name: 'MSCI', kw: ['msci'] },
  { name: 'FactSet', kw: ['factset'] },
  { name: 'Barclays', kw: ['barclays'] },
  { name: 'Deutsche Bank', kw: ['deutsche bank'] },
  { name: 'UBS', kw: ['ubs'] },
  { name: 'HSBC', kw: ['hsbc'] },
  { name: 'RBC', kw: ['royal bank of canada', 'rbc capital'] },
  { name: 'TD Bank', kw: ['td bank', 'toronto-dominion'] },

  // ── Insurance & benefits ────────────────────────────────────────
  { name: 'Allstate', kw: ['allstate'] },
  { name: 'State Farm', kw: ['state farm'] },
  { name: 'Progressive', kw: ['progressive insurance', 'progressive corp'] },
  { name: 'Liberty Mutual', kw: ['liberty mutual'] },
  { name: 'Travelers', kw: ['travelers companies', 'travelers insurance'] },
  { name: 'Chubb', kw: ['chubb'] },
  { name: 'AIG', kw: ['aig', 'american international group'] },
  { name: 'Nationwide', kw: ['nationwide insurance', 'nationwide mutual'] },
  { name: 'USAA', kw: ['usaa'] },
  { name: 'Aflac', kw: ['aflac'] },
  { name: 'Prudential', kw: ['prudential'] },
  { name: 'MetLife', kw: ['metlife'] },
  { name: 'Guardian Life', kw: ['guardian life'] },
  { name: 'Principal Financial', kw: ['principal financial'] },
  { name: 'Lincoln Financial', kw: ['lincoln financial'] },
  { name: 'TIAA', kw: ['tiaa'] },
  { name: 'New York Life', kw: ['new york life'] },
  { name: 'Northwestern Mutual', kw: ['northwestern mutual'] },
  { name: 'MassMutual', kw: ['massmutual', 'mass mutual'] },
  { name: 'Cigna', kw: ['cigna'] },
  { name: 'Humana', kw: ['humana'] },
  { name: 'Elevance Health', kw: ['elevance', 'anthem'] },
  { name: 'Marsh McLennan', kw: ['marsh mclennan', 'mercer'] },
  { name: 'Aon', kw: ['aon plc', 'aon corporation'] },

  // ── Pharma, biotech & healthcare ────────────────────────────────
  { name: 'Pfizer', kw: ['pfizer'] },
  { name: 'Merck', kw: ['merck'] },
  { name: 'Johnson & Johnson', kw: ['johnson & johnson', 'johnson and johnson'] },
  { name: 'AbbVie', kw: ['abbvie'] },
  { name: 'Amgen', kw: ['amgen'] },
  { name: 'Gilead', kw: ['gilead'] },
  { name: 'Bristol Myers Squibb', kw: ['bristol myers', 'bristol-myers'] },
  { name: 'Eli Lilly', kw: ['eli lilly', 'lilly'] },
  { name: 'Novartis', kw: ['novartis'] },
  { name: 'Genentech', kw: ['genentech', 'roche'] },
  { name: 'AstraZeneca', kw: ['astrazeneca'] },
  { name: 'GSK', kw: ['glaxosmithkline', 'gsk'] },
  { name: 'Sanofi', kw: ['sanofi'] },
  { name: 'Bayer', kw: ['bayer'] },
  { name: 'Biogen', kw: ['biogen'] },
  { name: 'Regeneron', kw: ['regeneron'] },
  { name: 'Vertex Pharmaceuticals', kw: ['vertex pharmaceuticals'] },
  { name: 'Moderna', kw: ['moderna'] },
  { name: 'Boston Scientific', kw: ['boston scientific'] },
  { name: 'Medtronic', kw: ['medtronic'] },
  { name: 'Abbott', kw: ['abbott'] },
  { name: 'Stryker', kw: ['stryker'] },
  { name: 'Becton Dickinson', kw: ['becton dickinson'] },
  { name: 'Baxter', kw: ['baxter'] },
  { name: 'Thermo Fisher', kw: ['thermo fisher'] },
  { name: 'Danaher', kw: ['danaher'] },
  { name: 'Illumina', kw: ['illumina'] },
  { name: 'Edwards Lifesciences', kw: ['edwards lifesciences'] },
  { name: 'McKesson', kw: ['mckesson'] },
  { name: 'Cardinal Health', kw: ['cardinal health'] },
  { name: 'Cencora', kw: ['cencora', 'amerisourcebergen'] },
  { name: 'HCA Healthcare', kw: ['hca healthcare'] },
  { name: 'UnitedHealth', kw: ['unitedhealth', 'optum'] },
  { name: 'CVS Health', kw: ['cvs health', 'cvs pharmacy', 'aetna'] },
  { name: 'Quest Diagnostics', kw: ['quest diagnostics'] },
  { name: 'Labcorp', kw: ['labcorp'] },
  { name: 'Zoetis', kw: ['zoetis'] },

  // ── Consumer goods, food & beverage ─────────────────────────────
  { name: 'Procter & Gamble', kw: ['procter & gamble', 'procter and gamble'] },
  { name: 'Unilever', kw: ['unilever'] },
  { name: 'Colgate-Palmolive', kw: ['colgate'] },
  { name: 'Kimberly-Clark', kw: ['kimberly-clark', 'kimberly clark'] },
  { name: 'Clorox', kw: ['clorox'] },
  { name: 'Church & Dwight', kw: ['church & dwight'] },
  { name: 'General Mills', kw: ['general mills'] },
  { name: 'Kellanova', kw: ['kellanova', 'kellogg'] },
  { name: 'Kraft Heinz', kw: ['kraft heinz', 'kraft foods'] },
  { name: 'Mondelez', kw: ['mondelez'] },
  { name: 'Mars', kw: ['mars incorporated', 'mars inc', 'mars wrigley'] },
  { name: 'Hershey', kw: ['hershey'] },
  { name: 'Nestlé', kw: ['nestle', 'nestlé'] },
  { name: 'Danone', kw: ['danone'] },
  { name: 'Estée Lauder', kw: ['estee lauder', 'estée lauder'] },
  { name: "L'Oréal", kw: ['oreal', 'l’oreal'] },
  { name: 'Coca-Cola', kw: ['coca-cola', 'coca cola'] },
  { name: 'PepsiCo', kw: ['pepsico', 'pepsi'] },
  { name: 'Keurig Dr Pepper', kw: ['keurig', 'dr pepper'] },
  { name: 'Constellation Brands', kw: ['constellation brands'] },
  { name: 'Anheuser-Busch', kw: ['anheuser-busch', 'anheuser busch'] },
  { name: 'Molson Coors', kw: ['molson coors'] },
  { name: 'Diageo', kw: ['diageo'] },

  // ── Retail, apparel, hospitality & restaurants ──────────────────
  { name: 'Walmart', kw: ['walmart'] },
  { name: 'Costco', kw: ['costco'] },
  { name: 'Target', kw: ['target corporation', 'target corp'] },
  { name: 'Kroger', kw: ['kroger'] },
  { name: 'Albertsons', kw: ['albertsons'] },
  { name: 'Walgreens', kw: ['walgreens'] },
  { name: "Lowe's", kw: ['lowe’s', "lowe's", 'lowes companies'] },
  { name: 'The Home Depot', kw: ['home depot'] },
  { name: 'Best Buy', kw: ['best buy'] },
  { name: "Macy's", kw: ['macy'] },
  { name: 'Nordstrom', kw: ['nordstrom'] },
  { name: 'TJX', kw: ['tjx', 't.j. maxx', 'tj maxx', 'marshalls'] },
  { name: 'Levi Strauss', kw: ['levi strauss', 'levi’s'] },
  { name: 'Ralph Lauren', kw: ['ralph lauren'] },
  { name: 'VF Corporation', kw: ['vf corporation'] },
  { name: 'Nike', kw: ['nike'] },
  { name: 'Under Armour', kw: ['under armour'] },
  { name: 'Lululemon', kw: ['lululemon'] },
  { name: 'Columbia Sportswear', kw: ['columbia sportswear'] },
  { name: "McDonald's", kw: ['mcdonald'] },
  { name: 'Starbucks', kw: ['starbucks'] },
  { name: 'Chipotle', kw: ['chipotle'] },
  { name: 'Yum! Brands', kw: ['yum brands', 'yum! brands'] },
  { name: 'Darden', kw: ['darden restaurants'] },
  { name: 'Marriott', kw: ['marriott'] },
  { name: 'Hilton', kw: ['hilton'] },
  { name: 'Hyatt', kw: ['hyatt'] },
  { name: 'IHG', kw: ['intercontinental hotels'] },

  // ── Industrial, energy, auto, aerospace & transport ─────────────
  { name: 'General Electric', kw: ['general electric'] },
  { name: 'Honeywell', kw: ['honeywell'] },
  { name: 'Emerson', kw: ['emerson electric'] },
  { name: 'Rockwell Automation', kw: ['rockwell automation'] },
  { name: 'Eaton', kw: ['eaton corporation', 'eaton corp'] },
  { name: 'Parker Hannifin', kw: ['parker hannifin'] },
  { name: 'Illinois Tool Works', kw: ['illinois tool works'] },
  { name: 'Caterpillar', kw: ['caterpillar'] },
  { name: 'John Deere', kw: ['john deere', 'deere & company'] },
  { name: 'Cummins', kw: ['cummins'] },
  { name: 'PACCAR', kw: ['paccar'] },
  { name: 'Lockheed Martin', kw: ['lockheed martin', 'lockheed'] },
  { name: 'Northrop Grumman', kw: ['northrop grumman', 'northrop'] },
  { name: 'RTX', kw: ['raytheon', 'rtx corporation'] },
  { name: 'General Dynamics', kw: ['general dynamics'] },
  { name: 'L3Harris', kw: ['l3harris', 'l-3 harris'] },
  { name: 'Boeing', kw: ['boeing'] },
  { name: '3M', kw: ['3m'] },
  { name: 'DuPont', kw: ['dupont'] },
  { name: 'Dow', kw: ['dow chemical', 'dow inc'] },
  { name: 'Corning', kw: ['corning'] },
  { name: 'PPG', kw: ['ppg industries'] },
  { name: 'Sherwin-Williams', kw: ['sherwin-williams', 'sherwin williams'] },
  { name: 'Ecolab', kw: ['ecolab'] },
  { name: 'Linde', kw: ['linde plc'] },
  { name: 'Air Products', kw: ['air products'] },
  { name: 'ExxonMobil', kw: ['exxonmobil', 'exxon'] },
  { name: 'Chevron', kw: ['chevron'] },
  { name: 'ConocoPhillips', kw: ['conocophillips'] },
  { name: 'Marathon Petroleum', kw: ['marathon petroleum'] },
  { name: 'Phillips 66', kw: ['phillips 66'] },
  { name: 'Valero', kw: ['valero'] },
  { name: 'SLB', kw: ['schlumberger', 'slb'] },
  { name: 'Halliburton', kw: ['halliburton'] },
  { name: 'Baker Hughes', kw: ['baker hughes'] },
  { name: 'Duke Energy', kw: ['duke energy'] },
  { name: 'Southern Company', kw: ['southern company'] },
  { name: 'NextEra Energy', kw: ['nextera'] },
  { name: 'Dominion Energy', kw: ['dominion energy'] },
  { name: 'Exelon', kw: ['exelon'] },
  { name: 'American Electric Power', kw: ['american electric power'] },
  { name: 'Ford', kw: ['ford motor'] },
  { name: 'General Motors', kw: ['general motors'] },
  { name: 'Toyota', kw: ['toyota'] },
  { name: 'Honda', kw: ['honda'] },
  { name: 'Stellantis', kw: ['stellantis', 'chrysler'] },
  { name: 'BMW', kw: ['bmw'] },
  { name: 'Mercedes-Benz', kw: ['mercedes-benz', 'mercedes benz'] },
  { name: 'Volkswagen', kw: ['volkswagen'] },
  { name: 'Delta Air Lines', kw: ['delta air lines'] },
  { name: 'United Airlines', kw: ['united airlines'] },
  { name: 'American Airlines', kw: ['american airlines'] },
  { name: 'Southwest Airlines', kw: ['southwest airlines'] },
  { name: 'FedEx', kw: ['fedex'] },
  { name: 'UPS', kw: ['united parcel', 'ups'] },
  { name: 'Union Pacific', kw: ['union pacific'] },

  // ── Telecom & media ─────────────────────────────────────────────
  { name: 'Verizon', kw: ['verizon'] },
  { name: 'AT&T', kw: ['at&t', 'at and t'] },
  { name: 'T-Mobile', kw: ['t-mobile', 't mobile'] },
  { name: 'Comcast', kw: ['comcast', 'nbcuniversal'] },
  { name: 'Charter', kw: ['charter communications', 'spectrum'] },
  { name: 'The Walt Disney Company', kw: ['walt disney', 'disney'] },
  { name: 'Warner Bros. Discovery', kw: ['warner bros', 'warner brothers'] },
  { name: 'Paramount', kw: ['paramount global', 'viacomcbs'] },
  { name: 'Spotify', kw: ['spotify'] },
  { name: 'Thomson Reuters', kw: ['thomson reuters'] },
  { name: 'RELX', kw: ['relx', 'lexisnexis', 'elsevier'] },
  { name: 'Nielsen', kw: ['nielsen'] },

  // ── Professional services & consulting ──────────────────────────
  { name: 'McKinsey', kw: ['mckinsey'] },
  { name: 'Boston Consulting Group', kw: ['boston consulting'] },
  { name: 'Bain & Company', kw: ['bain & company', 'bain and company'] },
  { name: 'Deloitte', kw: ['deloitte'] },
  { name: 'PwC', kw: ['pwc', 'pricewaterhousecoopers'] },
  { name: 'EY', kw: ['ernst & young', 'ernst and young'] },
  { name: 'KPMG', kw: ['kpmg'] },
  { name: 'Accenture', kw: ['accenture'] },
  { name: 'Booz Allen', kw: ['booz allen'] },
  { name: 'Capgemini', kw: ['capgemini'] },
  { name: 'Cognizant', kw: ['cognizant'] },
  { name: 'Infosys', kw: ['infosys'] },
  { name: 'Wipro', kw: ['wipro'] },
  { name: 'Tata Consultancy', kw: ['tata consultancy', 'tcs'] },
  { name: 'Gartner', kw: ['gartner'] },
];
